# Auto-report action script, 3 times a day

name: Auto-report action

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '1 16,12,3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run report script
      env:
        STUID: ${{ secrets.Stuid }}
        PASSWORD: ${{ secrets.Password }}
        BAIDU_API_KEY: ${{ secrets.Baidu_Api_Key }}
        BAIDU_API_SECRET_KEY: ${{ secrets.Baidu_Api_Secret_Key }}
      run: |
        python report.py data.json "$STUID" "$PASSWORD" "$BAIDU_API_KEY" "$BAIDU_API_SECRET_KEY"
